import {
	AtSign,
	Binary,
	Calendar,
	Check,
	ChevronRight,
	ChevronsUpDown,
	Circle,
	CircleCheck,
	Download,
	Eclipse,
	Ellipsis,
	Home,
	Languages,
	List,
	Loader2,
	LogOut,
	MessageCircleQuestionMark,
	Moon,
	Pencil,
	Plus,
	Pyramid,
	RectangleEllipsis,
	Search,
	Settings2,
	ShieldUser,
	Sparkle,
	Sun,
	Trash,
	Type,
	User,
	Warehouse,
	X,
} from 'lucide-react'

export const Icons = {
	moon: Moon,
	sun: Sun,
	sparkle: Sparkle,
	plus: Plus,
	home: Home,
	settings: Settings2,
	languages: Languages,
	help: MessageCircleQuestionMark,
	logout: LogOut,
	user: User,
	upDownChevron: ChevronsUpDown,
	eclipse: Eclipse,
	warehouse: Warehouse,
	check: Check,
	checkCircle: CircleCheck,
	loader: Loader2,
	shieldUser: ShieldUser,
	search: Search,
	download: Download,
	cross: X,
	circle: Circle,
	calendar: Calendar,
	pyramid: Pyramid,
	type: Type,
	list: List,
	ellipsis: Ellipsis,
	trash: Trash,
	pencil: Pencil,
	chevronRight: ChevronRight,
	pin: Binary,
	email: AtSign,
	password: RectangleEllipsis,
}
